"""Generate project-scoped Codex and Claude Code config without touching user-wide settings."""

from __future__ import annotations

import argparse
import copy
import json
import os
import re
import sys
import tomllib
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import ProxyHandler, Request, build_opener

if __package__:
    from .mcp_server import NoRedirect, ROOT, connection_options, default_data_dir, load_token
else:
    from mcp_server import NoRedirect, ROOT, connection_options, default_data_dir, load_token

START = "# BEGIN Agentboard MCP (generated by connectors/setup.py)"
END = "# END Agentboard MCP"


def codex_config(existing: str, entry: dict) -> str:
    """Replace only this server and validate that every other parsed setting survives."""
    before = tomllib.loads(existing)
    expected = copy.deepcopy(before)
    servers = expected.setdefault("mcp_servers", {})
    if not isinstance(servers, dict):
        raise ValueError("mcp_servers must be a TOML table")
    servers["agentboard"] = entry
    retained, dropping = [], False
    for line in existing.splitlines(keepends=True):
        stripped = line.strip()
        if stripped in {START, END}:
            continue
        if re.match(r"^\s*\[.+\]\s*(?:#.*)?$", line):
            header = tomllib.loads(line)
            dropping = isinstance(header.get("mcp_servers"), dict) and "agentboard" in header["mcp_servers"]
        if not dropping:
            retained.append(line)
    block = "\n".join([START, "[mcp_servers.agentboard]", *[
        f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in entry.items()
    ], END])
    candidate = "".join(retained).rstrip() + "\n\n" + block + "\n"
    if tomllib.loads(candidate) != expected:
        raise ValueError("Cannot safely update this TOML layout; existing config was left unchanged")
    return candidate


def save(path: Path, content: str, private: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".agentboard.tmp")
    temporary.write_text(content, encoding="utf-8")
    if private:
        os.chmod(temporary, 0o600)
    os.replace(temporary, path)


def setup(project_root: Path, credentials: Path | None = None, base_url: str | None = None,
          agent_name: str | None = None, agent_kind: str = "codex", *,
          executable: Path | None = None, data_dir: Path | None = None) -> tuple[Path, Path]:
    project_root = project_root.resolve()
    if getattr(sys, "frozen", False):
        executable = executable or Path(sys.executable)
        data_dir = data_dir or default_data_dir()
    credentials, base_url = connection_options(credentials, data_dir, base_url)
    if executable is not None:
        executable = executable.resolve()
        if not executable.is_file():
            raise ValueError("Agentboard executable does not exist")
        data_dir = (data_dir or credentials.parent).resolve()
    cwd = project_root if executable else ROOT
    for kind in ("codex", "claude"):
        load_token(kind, credentials)
    configs = {}
    for kind in ("codex", "claude"):
        configs[kind] = {
            "command": str(executable) if executable else sys.executable,
            "args": ["--mcp" if executable else str(ROOT / "connectors" / "mcp_server.py"),
                     "--agent", kind, "--credentials", str(credentials),
                     *(["--data-dir", str(data_dir)] if data_dir else ["--url", base_url])],
        }

    claude_path = project_root / ".mcp.json"
    codex_path = project_root / ".codex" / "config.toml"
    claude = json.loads(claude_path.read_text(encoding="utf-8-sig")) if claude_path.exists() else {}
    if not isinstance(claude, dict) or not isinstance(claude.setdefault("mcpServers", {}), dict):
        raise ValueError(".mcp.json must contain a mcpServers object")
    previous_codex = codex_path.read_text(encoding="utf-8-sig") if codex_path.exists() else ""
    codex = codex_config(previous_codex, {
        **configs["codex"], "cwd": str(cwd),
    })
    # Validate existing configuration before provisioning a one-time credential.
    token_path = None
    if agent_name:
        request = Request(base_url + "/api/agents", method="POST", headers={
            "Content-Type": "application/json", "X-Dashboard-Client": "browser",
        }, data=json.dumps({"name": agent_name, "kind": agent_kind,
                            "reason": "Отдельная идентичность экземпляра coding agent"}, ensure_ascii=False).encode("utf-8"))
        with build_opener(ProxyHandler({}), NoRedirect()).open(request, timeout=15) as response:
            issued = json.load(response)
        token_path = credentials.parent / f"agent-{issued['agent']['id']}.token"
        token = issued["token"]
        configs[agent_kind]["args"] += ["--token-file", str(token_path)]
        if agent_kind == "codex":
            codex = codex_config(previous_codex, {**configs["codex"], "cwd": str(cwd)})
    claude["mcpServers"]["agentboard"] = {"type": "stdio", **configs["claude"]}
    # Validate both config files before writing either one.
    if token_path:
        save(token_path, token + "\n", private=True)
    save(claude_path, json.dumps(claude, ensure_ascii=False, indent=2) + "\n")
    save(codex_path, codex)
    return claude_path, codex_path


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=Path.cwd() if getattr(sys, "frozen", False) else ROOT)
    parser.add_argument("--credentials", type=Path)
    parser.add_argument("--data-dir", type=Path, help="Desktop user's data directory, including runtime.json")
    parser.add_argument("--executable", type=Path, help="Installed Agentboard.exe for project MCP commands")
    parser.add_argument("--url", help="Explicit loopback URL; overrides desktop runtime discovery")
    parser.add_argument("--agent-name", help="Provision one separately attributed coding-agent instance")
    parser.add_argument("--agent", choices=["codex", "claude"], default="codex", help="Kind for --agent-name")
    args = parser.parse_args(argv)
    try:
        paths = setup(args.project_root, args.credentials, args.url, args.agent_name, args.agent,
                      executable=args.executable, data_dir=args.data_dir)
    except (OSError, ValueError, KeyError, HTTPError, URLError) as error:
        print(f"Agentboard setup: {error}", file=sys.stderr)
        raise SystemExit(1) from None
    for path in paths:
        print(f"Configured: {path}")
    print("Restart Codex/Claude Code, check the agentboard server in /mcp. Configuration is not proof of connection.")


if __name__ == "__main__":
    main()
